import type { WorkflowTemplate } from '@metamodels/connectors'
import { reconstructGraph, comfyuiConstraint, type ParamSpec } from '@metamodels/connectors'
import { graphSchema, templateDraftSchema, type TemplateDraft } from './template-schema'

export type BuildResult<T> = { ok: true; value: T } | { ok: false; reason: string }

/** Parse pasted workflow-API JSON into a validated graph, or a friendly reason. */
export function parseGraphText(text: string): BuildResult<WorkflowTemplate['graph']> {
  let raw: unknown
  try {
    raw = JSON.parse(text)
  } catch {
    return { ok: false, reason: 'graph is not valid JSON' }
  }
  const parsed = graphSchema.safeParse(raw)
  if (!parsed.success) return { ok: false, reason: 'not a valid workflow-API graph (each node needs class_type + inputs)' }
  return { ok: true, value: parsed.data }
}

/** Enumerate selectable binding targets: each node id with its input keys, deterministically sorted. */
export function graphTargets(graph: WorkflowTemplate['graph']): { node: string; inputs: string[] }[] {
  return Object.keys(graph)
    .sort()
    .map((node) => ({ node, inputs: Object.keys(graph[node].inputs).sort() }))
}

/** Assemble a draft into a WorkflowTemplate and validate it exactly as the data-plane will. */
export function buildTemplate(draft: TemplateDraft): BuildResult<WorkflowTemplate> {
  const parsedGraph = parseGraphText(draft.graphText)
  if (!parsedGraph.ok) return parsedGraph

  const names = draft.params.map((p) => p.name)
  const dup = names.find((n, i) => names.indexOf(n) !== i)
  if (dup) return { ok: false, reason: `duplicate param name: ${dup}` }

  const candidate = { id: draft.id, graph: parsedGraph.value, params: draft.params, cost: draft.cost }
  // Validate against the breed's own constraint so what we store is byte-identical
  // to what the data-plane re-parses. `.templates[0]` is the built template.
  const checked = comfyuiConstraint.safeParse({ templates: [candidate] })
  if (!checked.success) return { ok: false, reason: checked.error.issues[0]?.message ?? 'invalid template' }
  return { ok: true, value: checked.data.templates[0] }
}

/** Synthesize a sample value per non-seed param and reconstruct — proves every target resolves. */
export function dryRunTemplate(tpl: WorkflowTemplate): BuildResult<WorkflowTemplate['graph']> {
  const params: Record<string, unknown> = {}
  const uploads: Record<string, string> = {}
  for (const spec of tpl.params) sampleParam(spec, params, uploads)
  const out = reconstructGraph(tpl, params, { uploads, rng: () => 0.5 })
  if (!out.ok) return { ok: false, reason: out.reason }
  return { ok: true, value: out.graph }
}

function sampleParam(spec: ParamSpec, params: Record<string, unknown>, uploads: Record<string, string>): void {
  // seed is auto-generated by reconstructGraph — never supply it as a consumer value.
  if (spec.type === 'seed') return
  if (spec.type === 'text') params[spec.name] = 'sample'
  else if (spec.type === 'number') params[spec.name] = spec.min ?? 0
  else if (spec.type === 'image') {
    params[spec.name] = 'sample' // presence forces the image branch
    uploads[spec.name] = 'dry-run.png'
  }
}

/** Single entry point: parse the draft shape, build, and dry-run. Returns the storable template. */
export function validateDraft(draft: unknown): BuildResult<WorkflowTemplate> {
  const parsed = templateDraftSchema.safeParse(draft)
  if (!parsed.success) return { ok: false, reason: parsed.error.issues[0]?.message ?? 'invalid draft' }
  const built = buildTemplate(parsed.data)
  if (!built.ok) return built
  const dry = dryRunTemplate(built.value)
  if (!dry.ok) return dry
  return built
}
